---
- hosts: all
  become: true
  gather_facts: False

  vars:
    region: ap-south-1
    instance_type: t2.micro
    ami: ami-0cb0e70f44e1a4bb5
    hosts_file: /etc/ansible/hosts
    accesskey: AKIA4JTWZIAFLZJWJ24J
    secretkey: 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

  tasks:
  - name: Create security group
    ec2_group:
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: "johnson1"
      description: "johnson Security Group"
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

  - name: Create an EC2 key
    ec2_key:
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      name: "johnson1"
      region: "{{ region }}"
    register: ec2_key
  - name: Save private key (PEM file)
    copy: content="{{ ec2_key.key.private_key }}" dest=/etc/ansible/johnson1.pem mode=0600
    when: ec2_key.changed
  - name: Create an ec2 instance
    ec2:
      aws_access_key: "{{ accesskey }}"
      aws_secret_key: "{{ secretkey }}"
      key_name: johnson1
      group: johnson1 # security group name
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: true
      region: "{{ region }}"
      count: 1 
      count_tag:
        Name: Demo1
      instance_tags:
        Name: Demo1
    register: ec2
  - name: Save IP to inventory file
    lineinfile:
      dest: "{{ hosts_file }}"
      insertafter: '\[webservers\]'
      line: "{{ item.private_ip }}"
    with_items: "{{ ec2.instances }}"
